name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas en modo headless
        run: |
          pytest test_tienda.py --html=reporte_final.html --self-contained-html -v

      - name: Guardar reporte HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-selenium
          path: reporte_final.html
